### ISSUE TITLE
[Support] guard not picking up changes -getpgid not found

### ISSUE THREAD

**Issue by jonyeezs** [rchampourlier/guard-shotgun#10]
On windows 10.

When i exec guard this is what i see:

```
16:32:40 - INFO - Starting up Rack...
16:32:51 - ERROR - Guard::Shotgun failed to achieve its <start>, exception was:
> [#b6da0afb79d8] NotImplementedError: getpgid() function is unimplemented on this machine
> [#b6da0afb79d8] C:/Development/Ruby21/lib/ruby/gems/2.1.0/gems/guard-shotgun-0.4.0/lib/guard/shotgun.rb:108:in `getpgi
d'
> [#b6da0afb79d8] C:/Development/Ruby21/lib/ruby/gems/2.1.0/gems/guard-shotgun-0.4.0/lib/guard/shotgun.rb:108:in `runnin
g?'
> [#b6da0afb79d8] C:/Development/Ruby21/lib/ruby/gems/2.1.0/gems/guard-shotgun-0.4.0/lib/guard/shotgun.rb:40:in `start'
> [#b6da0afb79d8] C:/Development/Ruby21/lib/ruby/gems/2.1.0/gems/guard-2.13.0/lib/guard/runner.rb:82:in `block in _super
vise'
> [#b6da0afb79d8] C:/Development/Ruby21/lib/ruby/gems/2.1.0/gems/guard-2.13.0/lib/guard/runner.rb:79:in `catch'
> [#b6da0afb79d8] C:/Development/Ruby21/lib/ruby/gems/2.1.0/gems/guard-2.13.0/lib/guard/runner.rb:79:in `_supervise'
> [#b6da0afb79d8] C:/Development/Ruby21/lib/ruby/gems/2.1.0/gems/guard-2.13.0/lib/guard/runner.rb:22:in `block (3 levels
) in run'
> [#b6da0afb79d8] C:/Development/Ruby21/lib/ruby/gems/2.1.0/gems/guard-2.13.0/lib/guard/runner.rb:119:in `block (2 level
s) in _run_group_plugins'
> [#b6da0afb79d8] C:/Development/Ruby21/lib/ruby/gems/2.1.0/gems/guard-2.13.0/lib/guard/runner.rb:117:in `each'
> [#b6da0afb79d8] C:/Development/Ruby21/lib/ruby/gems/2.1.0/gems/guard-2.13.0/lib/guard/runner.rb:117:in `block in _run_
group_plugins'
> [#b6da0afb79d8] C:/Development/Ruby21/lib/ruby/gems/2.1.0/gems/guard-2.13.0/lib/guard/runner.rb:116:in `catch'
> [#b6da0afb79d8] C:/Development/Ruby21/lib/ruby/gems/2.1.0/gems/guard-2.13.0/lib/guard/runner.rb:116:in `_run_group_plu
gins'
> [#b6da0afb79d8] C:/Development/Ruby21/lib/ruby/gems/2.1.0/gems/guard-2.13.0/lib/guard/runner.rb:21:in `block (2 levels
) in run'
> [#b6da0afb79d8] C:/Development/Ruby21/lib/ruby/gems/2.1.0/gems/guard-2.13.0/lib/guard/runner.rb:20:in `each'
> [#b6da0afb79d8] C:/Development/Ruby21/lib/ruby/gems/2.1.0/gems/guard-2.13.0/lib/guard/runner.rb:20:in `block in run'
> [#b6da0afb79d8] C:/Development/Ruby21/lib/ruby/gems/2.1.0/gems/lumberjack-1.0.10/lib/lumberjack.rb:32:in `unit_of_work
'
> [#b6da0afb79d8] C:/Development/Ruby21/lib/ruby/gems/2.1.0/gems/guard-2.13.0/lib/guard/runner.rb:18:in `run'
> [#b6da0afb79d8] C:/Development/Ruby21/lib/ruby/gems/2.1.0/gems/guard-2.13.0/lib/guard/commander.rb:34:in `start'
> [#b6da0afb79d8] C:/Development/Ruby21/lib/ruby/gems/2.1.0/gems/guard-2.13.0/lib/guard/cli/environments/valid.rb:16:in
`start_guard'
> [#b6da0afb79d8] C:/Development/Ruby21/lib/ruby/gems/2.1.0/gems/guard-2.13.0/lib/guard/cli.rb:122:in `start'
> [#b6da0afb79d8] C:/Development/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
> [#b6da0afb79d8] C:/Development/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_comma
nd'
> [#b6da0afb79d8] C:/Development/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
> [#b6da0afb79d8] C:/Development/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
> [#b6da0afb79d8] C:/Development/Ruby21/lib/ruby/gems/2.1.0/gems/guard-2.13.0/lib/guard/aruba_adapter.rb:32:in `execute'

> [#b6da0afb79d8] C:/Development/Ruby21/lib/ruby/gems/2.1.0/gems/guard-2.13.0/lib/guard/aruba_adapter.rb:19:in `execute!
'
> [#b6da0afb79d8] C:/Development/Ruby21/lib/ruby/gems/2.1.0/gems/guard-2.13.0/bin/_guard-core:11:in `<main>'
16:32:52 - INFO - Guard::Shotgun has just been fired
```

It executes rackup just fine ( i can see my application running). But it won't do anything on any file changes.

How do I troubleshoot this?

**Comment by rchampourlier** [comment]
Hi @jonyeezs,

Sorry I don't fell like I can help you. Did you figure out? It's working fine on my environment, maybe something's related to Win10? Do other Guard plugins work?

Best,
